### ISSUE TITLE
Allow CustomChecks plugin to be disabled

### ISSUE THREAD

**Issue by jenspettersson** [Particular/ServiceControl.Plugin.Nsb6.CustomChecks#21]
CustomChecks plugin can now be disabled via code.

Here is an example:

``` c#
var endpointConfiguration = new EndpointConfiguration("my_endpoint");
endpointConfiguration.DisableFeature<CustomChecks>();
```
## 
# Original issue

When working in a codebase that is deployed to an instance using an Advanced License with ServiceControl but the developer only uses a Standard License and doesn't want/need SC locally, the Custom Check plugin causes a lot of errors (in our case, the bus doesn't always start and sometime, if it starts our legacy message handlers/satellites crashes when trying to build a dispatcher etc...). It actually throws errors for just being referenced, even if there is NO Custom Checks implemented at all.

With the Heartbeats plugin, we can always do:

`endpointConfiguration.DisableFeature<Heartbeats>();` when developing as the Heartbeats feature class is marked as public  (https://github.com/Particular/ServiceControl.Plugin.Nsb6.Heartbeat/blob/master/src/ServiceControl.Plugin.Nsb6.Heartbeat/Heartbeats.cs#L19)

However, that doesn't seem to be possible with the CustomChecks plugin:

https://github.com/Particular/ServiceControl.Plugin.Nsb6.CustomChecks/blob/master/src/ServiceControl.Plugin.CustomChecks/CustomChecks.cs#L11

A side note: The heartbeats plugin doesn't cause errors to be thrown when running the code on a Standard License without SC installed, only warnings, but that's not the case with CustomChecks...

Being able to disable CustomChecks via code would be perfect for us.

**Comment by timbussmann** [comment]
Since Heartbeats already does this, it seems to be the correct approach to fix up both issues for the CustomChecks plugin:
- Allow the Feature to be disabled
- Don't throw an exception in case the SC queue wasn't found (but log warnings, like the Heartbeats plugin)

@jenspettersson as a workaround until this has been addressed, can you try to create the SC queue manually (`Particular.ServiceControl` by default, or whatever you configured it to be)?

**Comment by jenspettersson** [comment]
@timbussmann the workaround doesn't work for us. Throws on start even if we've manually added the queue. However, we are in no need of CustomChecks at the moment so we will just remove the reference to the plugin for now.

**Comment by jenspettersson** [comment]
Just a bit more information:

On startup, every time (even though we have the Particular.ServiceControl queue manually created):

```
2016-10-19 14:12:21.939 ERROR NServiceBus This endpoint is unable to contact the ServiceControl Backend to report endpoint information. You have the ServiceControl plugins installed in your endpoint. However, please ensure that the Particul ar ServiceControl service is installed on this machine, or if running ServiceControl on a different machine, then ensure that your endpoint's app.config / web.config, AppSettings has the following key set appropriately: ServiceControl/Queue.
For example: <add key="ServiceControl/Queue" value="particular.servicecontrol@machine"/>
 Additional details: {0}
System.Exception: Message could not be routed to Particular.ServiceControl: 312 NO_ROUTE
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Plugin.ServiceControlBackend.<VerifyIfServiceControlQueueExists>d__5.MoveNext() in C:\Build\src\Shared\ServiceControlBackend.cs:line 144
```

And then, when it tries to enable our Satellite that consumes a "raw" RabbitMQ queue, this exception occurs MOST of the times:

```
2016-10-19 14:13:44.946 ERROR NServiceBus.StartableEndpoint Receiver LAB.LegacyQueue failed to start.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MessagePump'.
   at NServiceBus.Transport.RabbitMQ.MessagePump.ThrowIfDisposed()
   at NServiceBus.Transport.RabbitMQ.MessagePump.Start(PushRuntimeSettings limitations) in C:\Build\src\NServiceBus.Rabb
itMQ\Receiving\MessagePump.cs:line 0
   at NServiceBus.TransportReceiver.Start() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 45
   at NServiceBus.StartableEndpoint.StartReceivers(List`1 receivers) in C:\Build\src\NServiceBus.Core\StartableEndpoint.
cs:line 85
```

Sometimes the second exception doesn't occur, but then the satellite never even tries to start at all. It's a bit scary that the second exception only occurs randomly when starting the endpoint.

Removing the CustomChecks plugin reference makes everything run as normal again so that's what we'll do.

**Comment by timbussmann** [comment]
@jenspettersson Seeing that you're on RabbitMQ, I think you also need to create an Exchange with the same name as the configured SC queue (e.g. `Particular.ServiceControl` by default) (durable, fanout) and bind it to the queue. Can you check whether that would work as  workaround (besides not using the plugin in general).

As for the exception, I got similar exception when reproducing your issue locally, I'll have a closer look at that.

**Comment by timbussmann** [comment]
also note for the workaround to work properly, you need to define the local dummy SC queue manually due to a bug I just found. E.g. like this:

```
  <appSettings>
    <add key="ServiceControl/Queue" value="Particular.ServiceControl"/>
  </appSettings>
```

**Comment by timbussmann** [comment]
I raised a dedicated issue about not failing the endpoint here: #23 so we can focus on disabling the feature on this issue.

**Comment by jenspettersson** [comment]
FYI:

The workaround with both a fanout Exchange bound to a queue AND an appSettings key seems to work if you create them all manually. No warnings, no errors.

**Comment by timbussmann** [comment]
@jenspettersson after talking to @bording an exchange would already be enough.

@johnsimons I see that you added the 2.0 milestone. Is there a reason to not address this earlier in a minor version as this is a non-breaking change to make the feature public?

**Comment by jenspettersson** [comment]
@timbussmann Only an Exchange without a binding to a queue does not work.

So, for me to make it not fail (apart from just removing the reference all togheter) i need:
- Exchange: `Particular.ServiceControl - fanout`
- Queue: `Particular.ServiceControl`
- Binding between exchange to queue
- AppSetting: `<add key="ServiceControl/Queue" value="Particular.ServiceControl"/>`

If I remove one of these, it doesn't work.

**Comment by bording** [comment]
@jenspettersson You're correct, in this scenario you are going to need the queue & binding in addition to the exchange. The plugin needs to send messages to the configured queue, and the RabbitMQ transport sends commands with the `mandatory` flag set, so they will fail if there is no queue available.

My original comment to @timbussmann was more about general RabbitMQ behavior instead of being specific to our transport's behavior. Sorry for the confusion!

**Comment by johnsimons** [comment]
Added in https://github.com/Particular/ServiceControl.Plugin.Nsb6.CustomChecks/commit/ca75c4e4f817737195b27e05f74ffbd09a6795fb

**Comment by timbussmann** [comment]
@johnsimons is there any documentation planned, e.g. like here: https://docs.particular.net/servicecontrol/plugins/heartbeat#configuration-disabling-plugin

**Comment by johnsimons** [comment]
@timbussmann yes, the doco has been updated - https://docs.particular.net/servicecontrol/plugins/custom-checks#configuration-disabling-plugin
