### ISSUE TITLE
Plugin uses invalid ServiceControl queue name

### ISSUE THREAD

**Issue by timbussmann** [Particular/ServiceControl.Plugin.Nsb6.CustomChecks#22]
### Symptoms

The CustomChecks plugin contains logic to determine the machine name for the SC queue if the SC queue isn't configured explicitly. The queue name which is passed down to the transport can therefore look like this `Particular.ServiceControl@<some machine name>`. This value is invalid for most transports other than MSMQ and will cause the plugin to fail.
The endpoint crashes.
### Who's Affected

Users that are running v1.

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl.Plugin.Nsb6.CustomChecks/commit/ca75c4e4f817737195b27e05f74ffbd09a6795fb
